version: "3.7"

services:
  api:
    build: .
    volumes:
      - "./src/:/src/"
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  db:
    image: postgres:14.5-alpine3.16
    volumes:
      - "./data/pg/:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:7.0-alpine3.16
    volumes:
      - "./data/redis/:/data/"
    ports:
      - "6379:6379"
    command: --save 60 1
